import type { CourseMeta, CourseModule, QuizQuestion } from "@/lib/courses/types";

type ModuleBlueprint = {
  title: string;
  objective: string;
  summary: string;
  concepts: string[];
  practice: string;
  labTitle: string;
  labDescription: string;
  labSteps: string[];
  quiz: QuizQuestion;
};

export type FutureSkillCourse = {
  slug: string;
  title: string;
  shortTitle: string;
  summary: string;
  horizon: string;
  level: string;
  category: string;
  meta: CourseMeta;
  modules: CourseModule[];
};

function buildModules(slug: string, blueprints: ModuleBlueprint[]): CourseModule[] {
  return blueprints.map((module, index) => ({
    id: `${slug}-module-${index + 1}`,
    week: index + 1,
    title: module.title,
    objective: module.objective,
    lessons: [
      {
        id: `${slug}-m${index + 1}-concepts`,
        title: "Core Concepts",
        content: [module.summary],
        bullets: module.concepts,
      },
      {
        id: `${slug}-m${index + 1}-practice`,
        title: "Applied Practice",
        content: [module.practice],
      },
    ],
    lab: {
      title: module.labTitle,
      description: module.labDescription,
      steps: module.labSteps,
    },
    quiz: [module.quiz],
  }));
}

function course(
  slug: string,
  title: string,
  shortTitle: string,
  summary: string,
  horizon: string,
  level: string,
  category: string,
  objectives: string[],
  tools: { category: string; items: string }[],
  blueprints: ModuleBlueprint[]
): FutureSkillCourse {
  return {
    slug,
    title,
    shortTitle,
    summary,
    horizon,
    level,
    category,
    meta: {
      slug,
      title,
      tagline: `${horizon} future-skills track — learn durable concepts, build evidence, and adapt as tools change.`,
      duration: `${blueprints.length} modules`,
      pace: "4–6 hours/module",
      level,
      prerequisites: [
        "Basic digital literacy",
        "A browser and willingness to experiment",
        "No specialist hardware required for foundation labs unless stated",
      ],
      overview: [
        summary,
        "This course is deliberately capability-first: tools are examples, while the assessed skills are architecture, judgment, testing, documentation, security, and measurable problem solving.",
      ],
      objectives,
      tools,
      grading: [
        { component: "Module Labs", weight: "40%", detail: "Hands-on artifacts and documented experiments." },
        { component: "Module Quizzes", weight: "20%", detail: "Concept checks and scenario reasoning." },
        { component: "Portfolio Capstone", weight: "40%", detail: "A small, testable project with evidence, risks, and lessons learned." },
      ],
    },
    modules: buildModules(slug, blueprints),
  };
}

const responsibleAi = course(
  "responsible-ai-governance",
  "Responsible AI, Governance & AI Assurance",
  "Responsible AI & Governance",
  "Learn to inventory AI use, classify risk, evaluate systems, protect data, design meaningful human oversight, and produce audit-ready governance artifacts.",
  "2026–2035",
  "Intermediate",
  "AI Governance",
  [
    "Build an AI-use inventory and assign accountable owners.",
    "Classify AI risks by consequence, autonomy, data sensitivity, scale, and reversibility.",
    "Evaluate bias, privacy, security, transparency, and model-quality controls.",
    "Design human review, incident response, monitoring, and audit evidence.",
    "Create a practical AI governance starter pack for an organization.",
  ],
  [
    { category: "Frameworks", items: "NIST AI RMF concepts, ISO/IEC 42001 concepts, EU AI Act literacy, model cards" },
    { category: "Practice", items: "Risk registers, evaluation sets, AI inventories, incident logs, human-review checklists" },
  ],
  [
    {
      title: "AI Governance Foundations",
      objective: "Turn responsible-AI principles into ownership, purpose, boundaries, and evidence.",
      summary: "Governance starts before model selection. Teams need to know why an AI system exists, who is accountable, what data it may use, which people are affected, and what happens when it is wrong.",
      concepts: ["AI-use inventory", "accountable owner", "purpose limitation", "stakeholder mapping", "lifecycle governance"],
      practice: "Map one realistic AI use case from idea to retirement and identify the evidence that should exist at each stage.",
      labTitle: "Create an AI Use Inventory",
      labDescription: "Build a lightweight register for a five-tool organization.",
      labSteps: ["List five AI use cases", "Record owner, purpose, users, and data", "Classify business consequence", "Add review and retirement dates"],
      quiz: { question: "What is the strongest first governance control for an AI use case?", options: ["Choose the largest model", "Assign purpose and accountable ownership", "Automate every decision", "Hide model limitations"], answerIndex: 1, explanation: "Purpose and accountable ownership make later risk, review, and monitoring controls actionable." },
    },
    {
      title: "Risk Classification & Regulatory Literacy",
      objective: "Apply proportionate controls based on consequence rather than hype.",
      summary: "A brainstorming assistant and an automated employment decision should not receive the same controls. Risk classification considers impact, data sensitivity, autonomy, scale, affected people, and reversibility.",
      concepts: ["risk tiers", "high-impact use", "AI literacy", "proportionality", "documentation"],
      practice: "Compare three AI systems and justify why their approval, testing, and oversight requirements should differ.",
      labTitle: "Build a Risk Matrix",
      labDescription: "Score use cases and map each score to required controls.",
      labSteps: ["Define five risk factors", "Score four sample systems", "Set control thresholds", "Document exceptions and escalation"],
      quiz: { question: "Why should AI controls be proportionate?", options: ["All AI is equally risky", "It focuses stronger controls where consequences are higher", "It removes human oversight", "It guarantees legal compliance"], answerIndex: 1, explanation: "Proportionate governance strengthens high-consequence systems without blocking low-risk experimentation." },
    },
    {
      title: "Bias, Privacy & Data Governance",
      objective: "Identify data and fairness risks before they become product failures.",
      summary: "Bias can enter through data, labels, proxies, sampling, model behavior, or deployment context. Privacy risk grows when teams collect more personal information than a task actually needs.",
      concepts: ["data minimization", "proxy variables", "fairness testing", "retention", "access control"],
      practice: "Audit the inputs of a fictional hiring assistant and remove fields that create unnecessary privacy or discrimination risk.",
      labTitle: "Data & Fairness Review",
      labDescription: "Create a pre-deployment data review sheet.",
      labSteps: ["Classify data fields", "Identify unnecessary identifiers", "List plausible bias pathways", "Create a correction and appeal path"],
      quiz: { question: "Which practice most directly reduces unnecessary privacy exposure?", options: ["Collect every available field", "Data minimization", "Longer retention", "Shared admin accounts"], answerIndex: 1, explanation: "Data minimization reduces the information that must be protected and justified." },
    },
    {
      title: "Evaluation, Red Teaming & AI Assurance",
      objective: "Define what good looks like and test before trusting a system.",
      summary: "AI assurance combines representative test cases, groundedness checks, safety testing, adversarial scenarios, performance thresholds, and repeatable evidence. Evaluation must cover both normal and edge cases.",
      concepts: ["evaluation sets", "groundedness", "red teaming", "failure thresholds", "regression testing"],
      practice: "Create a ten-case evaluation set for a customer-support assistant, including ambiguous, adversarial, and insufficient-evidence cases.",
      labTitle: "Run an Assurance Gate",
      labDescription: "Define pass/fail criteria and a release decision.",
      labSteps: ["Write representative test cases", "Add two edge cases", "Score quality and safety", "Record failures and remediation"],
      quiz: { question: "What makes an AI evaluation useful over time?", options: ["Testing only easy examples", "Repeatable criteria and representative test cases", "Changing the metric after every run", "Ignoring failures"], answerIndex: 1, explanation: "Repeatable tests allow teams to compare versions and detect regressions." },
    },
    {
      title: "Human Oversight, Monitoring & Incidents",
      objective: "Design oversight that can genuinely change outcomes.",
      summary: "A human-in-the-loop label is weak if reviewers lack authority, evidence, time, or a clear escalation path. Production systems also need monitoring, incident logging, fallback procedures, and change control.",
      concepts: ["human approval", "override rate", "escalation", "incident response", "change management"],
      practice: "Design an approval workflow for a high-consequence AI recommendation and specify what evidence the reviewer sees.",
      labTitle: "Oversight & Incident Playbook",
      labDescription: "Create a one-page operating procedure for reviewers and incident owners.",
      labSteps: ["Define reviewer authority", "Set escalation thresholds", "Create an incident log", "Add fallback and recovery steps"],
      quiz: { question: "When is human oversight meaningful?", options: ["When a reviewer can change or stop the outcome", "When approval is automatic", "When no evidence is shown", "Only after an incident"], answerIndex: 0, explanation: "Oversight is effective only when the human has information and authority to influence the decision." },
    },
    {
      title: "Capstone: AI Governance Starter Pack",
      objective: "Produce a governance portfolio that a real team could use.",
      summary: "The capstone integrates inventory, risk classification, evaluation, privacy, oversight, transparency, monitoring, and incident response into a concise operating pack.",
      concepts: ["AI policy", "risk register", "model card", "evaluation report", "incident playbook"],
      practice: "Choose an education, finance, HR, health-administration, government, or small-business scenario and document a controlled deployment.",
      labTitle: "Publish the Governance Pack",
      labDescription: "Assemble the final portfolio artifact.",
      labSteps: ["Write a one-page policy", "Attach inventory and risk matrix", "Attach evaluation evidence", "Present residual risks and next review date"],
      quiz: { question: "What best demonstrates responsible-AI competence?", options: ["Memorizing ethics terms", "Producing usable governance artifacts tied to a real workflow", "Using the newest model", "Removing all human review"], answerIndex: 1, explanation: "Employable governance skill is demonstrated through evidence and controls that teams can actually operate." },
    },
  ]
);

const noCodeAutomation = course(
  "no-code-low-code-automation",
  "No-Code, Low-Code & Intelligent Workflow Automation",
  "No-Code & Automation",
  "Turn manual processes into reliable apps and automations using workflow logic, databases, APIs, permissions, AI-assisted building, and failure-aware operations.",
  "2026–2035",
  "Beginner to Intermediate",
  "Automation",
  [
    "Map and simplify a manual process before automating it.",
    "Design records, relationships, states, roles, and permissions.",
    "Connect APIs, webhooks, forms, notifications, and AI steps.",
    "Build internal tools and case-management workflows.",
    "Test retries, duplicate prevention, logs, and human approvals.",
  ],
  [
    { category: "Builders", items: "Bubble, Retool, Power Apps, AppSheet or equivalent visual builders" },
    { category: "Automation", items: "n8n, Make, Zapier, webhooks, REST APIs, structured AI outputs" },
  ],
  [
    {
      title: "Process Mapping Before Automation",
      objective: "Automate a good process instead of digitizing confusion.",
      summary: "Reliable automation begins with the current workflow: trigger, actors, decisions, data, handoffs, exceptions, and success criteria. Unnecessary steps should be removed before software is introduced.",
      concepts: ["trigger", "state", "handoff", "exception", "success metric"],
      practice: "Map a real intake process currently handled through forms, paper, email, or messaging and identify avoidable steps.",
      labTitle: "Workflow Blueprint",
      labDescription: "Turn one manual process into a clear automation map.",
      labSteps: ["Draw the current flow", "Remove redundant steps", "Define trigger and end state", "List failure and escalation paths"],
      quiz: { question: "What should happen before automating a messy process?", options: ["Add more tools", "Simplify and define the process", "Remove all approvals", "Buy a larger database"], answerIndex: 1, explanation: "Automation magnifies process quality, so unclear workflows should be redesigned first." },
    },
    {
      title: "Data Models, Forms & Permissions",
      objective: "Design the information layer behind a visual app.",
      summary: "No-code does not remove data architecture. Builders still need records, IDs, relationships, validation, states, access rules, and audit-friendly timestamps.",
      concepts: ["entities", "relationships", "validation", "role-based access", "audit fields"],
      practice: "Design a simple case-management model with users, cases, status history, notes, and attachments.",
      labTitle: "Build a Case Data Model",
      labDescription: "Create a small schema and permission matrix.",
      labSteps: ["Define entities", "Add unique IDs", "Map relationships", "Specify who can read and write each field"],
      quiz: { question: "Why are unique IDs important in workflow apps?", options: ["They make buttons colorful", "They reliably identify records across steps and integrations", "They replace permissions", "They eliminate backups"], answerIndex: 1, explanation: "Stable identifiers prevent records from being confused when data moves between systems." },
    },
    {
      title: "APIs, Webhooks & Integrations",
      objective: "Connect visual apps to the wider digital ecosystem.",
      summary: "APIs and webhooks connect forms and apps to payments, email, maps, storage, databases, and AI services. Builders must understand methods, authentication, payloads, responses, status codes, and rate limits.",
      concepts: ["REST API", "webhook", "authentication", "JSON", "rate limit"],
      practice: "Read one public API response, extract required fields, and define how errors should be handled.",
      labTitle: "Integration Chain",
      labDescription: "Connect an intake event to two downstream actions using dummy data.",
      labSteps: ["Define request and response", "Validate required fields", "Add a webhook action", "Handle non-2xx responses"],
      quiz: { question: "What is a webhook best described as?", options: ["A scheduled spreadsheet", "An event-driven HTTP notification", "A password manager", "A database index"], answerIndex: 1, explanation: "Webhooks let one system notify another when an event happens." },
    },
    {
      title: "Reliable Automation & Observability",
      objective: "Make invisible workflows safe to operate.",
      summary: "Production automations need idempotency, retry rules, logs, alerts, dead-letter handling, and clear ownership. Repeating a failed step must not create duplicate charges or records.",
      concepts: ["idempotency", "retry", "logging", "alerting", "duplicate prevention"],
      practice: "Review a payment-confirmation workflow and identify where retries could create harmful duplicate actions.",
      labTitle: "Failure-Ready Automation",
      labDescription: "Add observability and recovery to a workflow.",
      labSteps: ["Add a unique operation key", "Define retry limits", "Log each step", "Notify a human when recovery fails"],
      quiz: { question: "What does idempotency protect against?", options: ["Responsive design bugs", "Harmful duplicate effects when an operation repeats", "Weak passwords", "Slow typing"], answerIndex: 1, explanation: "Idempotent operations can safely be retried without duplicating their business effect." },
    },
    {
      title: "AI-Assisted App Building & Human Approval",
      objective: "Use generative builders without surrendering product judgment.",
      summary: "AI can propose interfaces, schemas, formulas, and workflow logic, but generated systems still need security review, user testing, permission checks, validation, and human approval for irreversible actions.",
      concepts: ["AI app builder", "structured output", "human approval", "security review", "usability testing"],
      practice: "Generate a prototype from a natural-language specification, then audit what the generator assumed incorrectly.",
      labTitle: "Prompt-to-App Audit",
      labDescription: "Build fast, then verify deliberately.",
      labSteps: ["Write a product specification", "Generate a first version", "Test permissions and edge cases", "Document fixes before release"],
      quiz: { question: "What remains the builder's responsibility when AI generates an app?", options: ["Nothing", "Security, data rules, usability, testing, and consequences", "Only the logo", "Only the prompt length"], answerIndex: 1, explanation: "Generation accelerates implementation but does not transfer accountability." },
    },
    {
      title: "Capstone: Operational Case Engine",
      objective: "Build a complete small workflow that solves a recurring problem.",
      summary: "The capstone combines intake, validation, case status, role-based access, notifications, AI-assisted classification, approvals, audit history, and failure handling.",
      concepts: ["case management", "SLA", "role permissions", "automation", "audit trail"],
      practice: "Choose admissions, research services, repairs, logistics, grants, business support, or another local workflow and build the smallest usable system.",
      labTitle: "Ship a Case Engine",
      labDescription: "Deliver a tested portfolio project for five realistic scenarios.",
      labSteps: ["Create intake and status flow", "Add roles and approvals", "Add one integration and one AI step", "Test five scenarios and publish results"],
      quiz: { question: "What is the strongest capstone evidence?", options: ["A screenshot only", "A working workflow with tests, failure handling, and user evidence", "A list of tools", "A long prompt"], answerIndex: 1, explanation: "A tested workflow demonstrates system thinking rather than interface familiarity." },
    },
  ]
);

const cloudArchitecture = course(
  "cloud-serverless-architecture",
  "Cloud Computing, Serverless & Modern Architecture",
  "Cloud & Serverless Architecture",
  "Understand how modern products run: compute, storage, databases, networks, identity, serverless functions, observability, cost control, reliability, and secure deployment.",
  "2026–2035",
  "Beginner to Intermediate",
  "Cloud",
  [
    "Explain core cloud service and deployment models.",
    "Design identity, network, storage, and database boundaries.",
    "Deploy serverless APIs and web applications safely.",
    "Use logs, metrics, alerts, backups, and cost controls.",
    "Create a small production architecture with least privilege.",
  ],
  [
    { category: "Cloud", items: "AWS, Azure, Google Cloud concepts; Vercel/serverless patterns" },
    { category: "Operations", items: "IAM, object storage, managed databases, functions, logs, metrics, budgets, backups" },
  ],
  [
    {
      title: "Cloud Foundations & Shared Responsibility",
      objective: "Understand what the provider manages and what the builder still owns.",
      summary: "Cloud literacy covers compute, storage, databases, networking, regions, availability, and service models. Managed infrastructure reduces operational work but never removes responsibility for identities, data, configuration, and application security.",
      concepts: ["IaaS/PaaS/SaaS", "region", "availability", "shared responsibility", "managed service"],
      practice: "Classify the components of a simple web application by what the provider manages and what the application team manages.",
      labTitle: "Architecture Map",
      labDescription: "Draw a cloud architecture for a small learning app.",
      labSteps: ["Map client and API", "Choose storage and database", "Mark trust boundaries", "Document provider vs team responsibilities"],
      quiz: { question: "What does shared responsibility mean in cloud computing?", options: ["The provider secures everything", "Security duties are divided between provider and customer", "Customers manage datacenters", "No one owns configuration"], answerIndex: 1, explanation: "Managed cloud services split responsibilities; customer configuration and data protection still matter." },
    },
    {
      title: "Identity, Secrets & Network Boundaries",
      objective: "Make identity the first security perimeter.",
      summary: "Modern cloud systems rely on roles, service identities, least privilege, secret management, network boundaries, and environment separation rather than shared administrator credentials.",
      concepts: ["IAM", "least privilege", "secrets", "network segmentation", "environment separation"],
      practice: "Design separate development and production access for a small team without sharing root or administrator credentials.",
      labTitle: "Least-Privilege Matrix",
      labDescription: "Map users and services to only the permissions they need.",
      labSteps: ["List roles", "List required actions", "Remove broad permissions", "Define secret rotation and offboarding"],
      quiz: { question: "Which access pattern is safest?", options: ["One shared admin login", "Least-privilege roles with separate identities", "Secrets in frontend code", "Permanent root access"], answerIndex: 1, explanation: "Separate least-privilege identities reduce blast radius and improve accountability." },
    },
    {
      title: "Storage, Databases & Data Lifecycle",
      objective: "Choose data services based on access patterns and durability needs.",
      summary: "Applications often combine object storage, relational or document databases, caches, and backups. Good design considers schema, query patterns, retention, encryption, replication, and recovery before scale arrives.",
      concepts: ["object storage", "relational vs document", "backup", "retention", "encryption"],
      practice: "Choose storage for profile data, uploaded documents, analytics events, and temporary cache entries, explaining the trade-offs.",
      labTitle: "Data Service Decision",
      labDescription: "Create a storage matrix for four data types.",
      labSteps: ["List data types", "Choose service type", "Set retention and backup", "Document access and encryption"],
      quiz: { question: "Which service is usually best for large uploaded files?", options: ["Object storage", "A DNS record", "A log label", "A CSS file"], answerIndex: 0, explanation: "Object storage is designed for durable blobs such as documents, media, and backups." },
    },
    {
      title: "Serverless, APIs & Event-Driven Systems",
      objective: "Build services that scale without managing long-lived servers.",
      summary: "Serverless functions and event-driven architectures are effective for web APIs, webhooks, scheduled jobs, and bursty workloads. Builders still need timeouts, idempotency, connection management, and observability.",
      concepts: ["serverless function", "cold start", "event", "webhook", "connection pooling"],
      practice: "Design a registration API that writes to a managed database and sends a welcome event without blocking the user request unnecessarily.",
      labTitle: "Deploy a Serverless API",
      labDescription: "Build a small health endpoint and one data endpoint.",
      labSteps: ["Create API handler", "Read environment variables", "Connect to managed data", "Test success and failure responses"],
      quiz: { question: "Which workload fits serverless especially well?", options: ["A physical network cable", "Event-driven HTTP and background functions", "A paper archive", "A monitor stand"], answerIndex: 1, explanation: "Serverless is well suited to request-driven and event-driven compute with variable demand." },
    },
    {
      title: "Reliability, Observability & FinOps",
      objective: "Operate what you deploy and control cost surprises.",
      summary: "Logs, metrics, traces, health checks, alerts, budgets, quotas, backups, and recovery tests turn deployment into an operable service. Cost is an architectural metric, not only a billing concern.",
      concepts: ["logs", "metrics", "alerts", "RTO/RPO", "FinOps"],
      practice: "Define the five most useful signals and a monthly spending guardrail for a small production application.",
      labTitle: "Operations Dashboard",
      labDescription: "Create an operational checklist and alert plan.",
      labSteps: ["Define health metrics", "Set error alerts", "Set budget alerts", "Write backup and restore test steps"],
      quiz: { question: "Why should a backup be restored during testing?", options: ["To make it larger", "To verify recovery actually works", "To remove logs", "To disable encryption"], answerIndex: 1, explanation: "A backup is only useful when recovery is proven." },
    },
    {
      title: "Capstone: Production-Ready Cloud Service",
      objective: "Combine architecture, security, deployment, observability, and cost control.",
      summary: "The capstone deploys a small service with managed data, least-privilege secrets, serverless compute, logs, a health check, backups, and a simple architecture decision record.",
      concepts: ["architecture decision record", "production readiness", "least privilege", "observability", "cost guardrail"],
      practice: "Deploy a small public service using free or low-cost tiers and document why each component was selected.",
      labTitle: "Cloud Launch Review",
      labDescription: "Ship and review a complete small architecture.",
      labSteps: ["Deploy the service", "Run security and failure checks", "Set alerts and budget", "Publish architecture and trade-offs"],
      quiz: { question: "What makes a cloud project production-ready?", options: ["It deploys once", "It combines security, reliability, observability, recovery, and cost controls", "It uses the most services possible", "It has no documentation"], answerIndex: 1, explanation: "Production readiness is operational, not merely deployment success." },
    },
  ]
);

const cyberAiCloud = course(
  "cybersecurity-ai-cloud",
  "Cybersecurity with AI & Cloud Defense",
  "Cybersecurity, AI & Cloud",
  "Develop defensive threat literacy across identity, cloud, applications, AI systems, incident response, and security operations without relying on one vendor or tool.",
  "2026–2035",
  "Intermediate",
  "Cybersecurity",
  [
    "Apply zero-trust and identity-first security principles.",
    "Recognize common cloud, application, social-engineering, and AI-system threats.",
    "Design secure configurations, logging, backups, and incident response.",
    "Evaluate prompt injection, data leakage, insecure tool use, and model-supply risks.",
    "Build a defensive monitoring and response capstone.",
  ],
  [
    { category: "Defensive Security", items: "IAM, MFA/passkeys, secure configuration, logs, SIEM concepts, incident response" },
    { category: "AI Security", items: "Prompt-injection defenses, tool permissions, data leakage controls, model/system evaluation" },
  ],
  [
    {
      title: "Threat Literacy & Zero Trust",
      objective: "Reason about attack paths rather than memorizing products.",
      summary: "Modern security assumes identities, devices, networks, and suppliers can be compromised. Zero trust emphasizes explicit verification, least privilege, segmentation, and continuous review.",
      concepts: ["attack surface", "zero trust", "MFA/passkeys", "least privilege", "social engineering"],
      practice: "Threat-model a small business that uses email, cloud storage, online banking, and a public website.",
      labTitle: "Attack Surface Inventory",
      labDescription: "Map identities, devices, data, and third-party dependencies.",
      labSteps: ["List critical assets", "Identify entry points", "Rank plausible threats", "Add preventive and recovery controls"],
      quiz: { question: "What is a core zero-trust idea?", options: ["Trust all internal traffic", "Verify explicitly and grant minimum necessary access", "Share administrator accounts", "Disable logs"], answerIndex: 1, explanation: "Zero trust reduces implicit trust and limits access to what is needed for each action." },
    },
    {
      title: "Identity, Cloud & Application Security",
      objective: "Protect the control plane and the software users depend on.",
      summary: "Cloud incidents often begin with stolen credentials, exposed secrets, insecure permissions, vulnerable dependencies, or misconfiguration. Application security adds validation, authorization, secure sessions, and dependency management.",
      concepts: ["IAM", "secret management", "authorization", "dependency risk", "secure configuration"],
      practice: "Audit a fictional deployment for public buckets, over-privileged roles, hard-coded secrets, and missing authorization checks.",
      labTitle: "Configuration Review",
      labDescription: "Create a secure-baseline checklist for a web application.",
      labSteps: ["Review identities", "Review secrets", "Review public exposure", "Review patch and dependency process"],
      quiz: { question: "Where should production secrets be stored?", options: ["Client-side JavaScript", "A managed secret/environment system with restricted access", "Public README", "Source-code comments"], answerIndex: 1, explanation: "Secrets should remain server-side and access-controlled." },
    },
    {
      title: "Securing AI & Agentic Systems",
      objective: "Protect systems where model output can trigger real actions.",
      summary: "AI systems add prompt injection, malicious retrieved content, sensitive-data leakage, unsafe tool calls, excessive autonomy, model-supply risks, and unreliable output to the traditional security surface.",
      concepts: ["prompt injection", "tool permissions", "RAG poisoning", "data leakage", "human approval"],
      practice: "Review an AI support agent that can read customer data and issue refunds, then reduce its permissions and add approval gates.",
      labTitle: "Agent Security Boundary",
      labDescription: "Design safe read/write permissions and untrusted-content handling.",
      labSteps: ["Classify trusted vs untrusted input", "Separate read and write tools", "Require approval for money or deletion", "Log high-impact actions"],
      quiz: { question: "What is the safest default for an AI agent's permissions?", options: ["Administrator access", "Minimum tools and permissions needed for the task", "Public database write access", "No action logs"], answerIndex: 1, explanation: "Least privilege limits damage when a model or input behaves unexpectedly." },
    },
    {
      title: "Detection, Logs & Security Operations",
      objective: "Use evidence to notice abnormal behavior early.",
      summary: "Security operations combines useful logs, alert rules, baselines, triage, and investigation. AI can assist with summarization and correlation, but analysts must verify evidence and avoid automating destructive responses blindly.",
      concepts: ["telemetry", "SIEM", "baseline", "alert triage", "false positive"],
      practice: "Design alerts for repeated failed logins, unexpected administrator changes, unusual data downloads, and disabled MFA.",
      labTitle: "Mini SOC Dashboard",
      labDescription: "Define events, severity, owner, and first response.",
      labSteps: ["Choose five security events", "Set severity rules", "Define investigation fields", "Create escalation paths"],
      quiz: { question: "Why is a baseline useful in detection?", options: ["It removes all alerts", "It helps distinguish normal behavior from meaningful anomalies", "It replaces authentication", "It hides incidents"], answerIndex: 1, explanation: "Detection improves when teams understand normal activity and can recognize deviations." },
    },
    {
      title: "Incident Response, Recovery & Resilience",
      objective: "Prepare decisions before a stressful incident occurs.",
      summary: "A response plan identifies reporting, containment, evidence preservation, communication, recovery, and lessons learned. Backups, credential recovery, supplier contacts, and tabletop exercises reduce chaos.",
      concepts: ["containment", "evidence preservation", "recovery", "tabletop exercise", "post-incident review"],
      practice: "Run a tabletop scenario for a compromised administrator account and suspicious payment-change request.",
      labTitle: "Incident Playbook",
      labDescription: "Create a practical first-hour response plan.",
      labSteps: ["Assign roles", "Define containment", "Preserve evidence", "Plan recovery and communication"],
      quiz: { question: "What should an incident plan define before an incident?", options: ["Only a logo", "Roles, reporting, containment, recovery, and communication", "A new password for everyone in public", "No escalation"], answerIndex: 1, explanation: "Prepared roles and steps reduce delay and destructive improvisation." },
    },
    {
      title: "Capstone: Hybrid Defense Architecture",
      objective: "Integrate identity, cloud, application, AI, monitoring, and recovery controls.",
      summary: "The capstone builds a defensive architecture for a realistic small organization and demonstrates how preventive, detective, responsive, and recovery controls cooperate.",
      concepts: ["defense in depth", "security architecture", "AI security", "incident response", "business resilience"],
      practice: "Choose an education, retail, research, logistics, or professional-services scenario and build its security map.",
      labTitle: "Defend a Digital Business",
      labDescription: "Publish a security architecture and tabletop evidence.",
      labSteps: ["Map critical assets", "Apply identity and app controls", "Add AI security and monitoring", "Run one incident scenario and document improvements"],
      quiz: { question: "What is defense in depth?", options: ["One perfect control", "Multiple complementary controls across prevention, detection, response, and recovery", "No backups", "Only antivirus"], answerIndex: 1, explanation: "Layered controls reduce dependence on any single safeguard." },
    },
  ]
);

const quantum = course(
  "quantum-post-quantum-readiness",
  "Quantum Computing & Post-Quantum Readiness",
  "Quantum & Post-Quantum",
  "Build practical literacy in qubits, quantum circuits, hybrid algorithms, real-hardware constraints, and the migration implications of post-quantum cryptography.",
  "2028–2040",
  "Intermediate",
  "Frontier Computing",
  [
    "Explain qubits, gates, measurement, entanglement, and noise.",
    "Build and simulate small quantum circuits.",
    "Recognize where quantum algorithms may offer advantage and where they do not.",
    "Understand why cryptographic migration must begin before fault-tolerant quantum computers arrive.",
    "Create a quantum-readiness assessment for an organization.",
  ],
  [
    { category: "Quantum", items: "Qiskit/Cirq concepts, cloud quantum simulators, hybrid classical-quantum workflows" },
    { category: "Security", items: "Post-quantum cryptography concepts, crypto inventory, migration planning" },
  ],
  [
    {
      title: "Qubits, Gates & Measurement",
      objective: "Understand the computational model without treating quantum as magic.",
      summary: "Quantum computation uses states, amplitudes, gates, measurement, and interference. Superposition does not mean reading all answers at once; algorithms must shape probability so useful results become more likely.",
      concepts: ["qubit", "superposition", "measurement", "quantum gate", "interference"],
      practice: "Simulate a one- and two-qubit circuit and compare the expected probability distribution with repeated measurements.",
      labTitle: "First Quantum Circuit",
      labDescription: "Create and measure a small circuit in a simulator.",
      labSteps: ["Initialize qubits", "Apply gates", "Measure repeatedly", "Explain the observed distribution"],
      quiz: { question: "What does measurement do to a qubit state?", options: ["It reveals every possible branch", "It produces a classical outcome according to the state's probabilities", "It adds storage", "It encrypts the circuit"], answerIndex: 1, explanation: "Measurement converts the quantum state into observed classical outcomes probabilistically." },
    },
    {
      title: "Entanglement, Noise & Real Hardware",
      objective: "Understand why today's quantum machines are constrained.",
      summary: "Entanglement creates correlations that classical descriptions cannot reproduce simply, while noise and decoherence limit useful circuit depth. Real devices require calibration-aware experiments and realistic expectations.",
      concepts: ["entanglement", "decoherence", "noise", "circuit depth", "error mitigation"],
      practice: "Create a Bell-state experiment in simulation, then reason about how noise would alter observed results.",
      labTitle: "Bell Pair Experiment",
      labDescription: "Build, measure, and interpret an entangled pair.",
      labSteps: ["Create superposition", "Entangle two qubits", "Measure correlations", "Document noise assumptions"],
      quiz: { question: "Why are deep circuits difficult on current hardware?", options: ["Screens are too small", "Noise and decoherence accumulate", "Qubits cannot be measured", "Classical computers disappear"], answerIndex: 1, explanation: "Current devices are noisy, so longer circuits accumulate errors." },
    },
    {
      title: "Quantum Algorithms & Hybrid Workflows",
      objective: "Separate promising algorithmic ideas from unrealistic speedup claims.",
      summary: "Grover-style search, Shor-style factoring, quantum simulation, and variational methods illustrate different forms of quantum advantage. Near-term work is often hybrid, with classical systems optimizing or interpreting quantum subroutines.",
      concepts: ["Grover", "Shor", "variational algorithm", "hybrid compute", "quantum advantage"],
      practice: "Choose a problem and explain whether a known quantum approach meaningfully changes complexity or merely adds novelty.",
      labTitle: "Algorithm Suitability Review",
      labDescription: "Compare classical and quantum approaches to one problem.",
      labSteps: ["Define the problem", "Identify a candidate algorithm", "State hardware assumptions", "Explain expected benefit and limitations"],
      quiz: { question: "What is a hybrid quantum workflow?", options: ["Only quantum hardware", "Classical computation working with quantum subroutines", "A blockchain", "A spreadsheet macro"], answerIndex: 1, explanation: "Many practical quantum workflows combine classical optimization and control with quantum circuits." },
    },
    {
      title: "Quantum Software & Cloud Access",
      objective: "Use software abstractions to experiment without owning quantum hardware.",
      summary: "Quantum SDKs express circuits, execute simulators or cloud QPUs, collect measurement results, and support transpilation for device constraints. Reproducibility requires recording backend, shots, seed, and circuit version.",
      concepts: ["SDK", "simulator", "QPU", "transpilation", "shots"],
      practice: "Create an experiment plan that can run first in simulation and later on available cloud hardware.",
      labTitle: "Cloud QPU Experiment Plan",
      labDescription: "Prepare a reproducible small quantum experiment.",
      labSteps: ["Write circuit", "Run simulator", "Select hardware backend", "Compare results and document noise"],
      quiz: { question: "What are 'shots' in a quantum experiment?", options: ["Image files", "Repeated executions used to estimate outcome probabilities", "Passwords", "Database rows"], answerIndex: 1, explanation: "Quantum results are statistical, so repeated shots estimate the output distribution." },
    },
    {
      title: "Post-Quantum Cryptography & Migration",
      objective: "Prepare for cryptographic change before an emergency deadline.",
      summary: "Large fault-tolerant quantum computers could threaten widely used public-key systems. Organizations therefore need cryptographic inventories, vendor plans, data-lifetime analysis, and migration paths to standardized post-quantum algorithms.",
      concepts: ["cryptographic inventory", "PQC", "harvest-now-decrypt-later", "crypto agility", "migration"],
      practice: "Inventory where an organization uses public-key cryptography and rank systems by data sensitivity and replacement difficulty.",
      labTitle: "Quantum Readiness Register",
      labDescription: "Create a migration-oriented cryptographic inventory.",
      labSteps: ["List cryptographic dependencies", "Classify data lifetime", "Identify vendor dependencies", "Prioritize migration and testing"],
      quiz: { question: "Why can post-quantum planning matter before a cryptographically relevant quantum computer exists?", options: ["Migrations take time and some encrypted data must remain secret for years", "All current encryption already fails", "Quantum hardware is required for websites", "Passwords stop working tomorrow"], answerIndex: 0, explanation: "Long migration cycles and long-lived sensitive data make early inventory and crypto agility valuable." },
    },
    {
      title: "Capstone: Quantum Opportunity & Risk Brief",
      objective: "Create a balanced decision document for a real sector.",
      summary: "The capstone combines technical literacy, experiment evidence, use-case screening, hardware constraints, and post-quantum migration into a practical executive brief.",
      concepts: ["use-case screening", "technical evidence", "PQC roadmap", "risk", "decision memo"],
      practice: "Choose finance, logistics, chemistry, energy, cybersecurity, or research and assess one opportunity plus one migration risk.",
      labTitle: "Quantum Readiness Brief",
      labDescription: "Publish a decision-ready portfolio artifact.",
      labSteps: ["Run one circuit experiment", "Assess one use case", "Build a crypto inventory sample", "Recommend next actions without hype"],
      quiz: { question: "What is the best quantum-readiness posture today?", options: ["Assume quantum solves everything", "Experiment selectively while building cryptographic agility and realistic evidence", "Replace every classical system", "Ignore cryptographic dependencies"], answerIndex: 1, explanation: "Balanced readiness combines experimentation with practical security migration planning." },
    },
  ]
);

const greenEdge = course(
  "green-tech-edge-ai",
  "Sustainable Technology, Edge AI & Intelligent IoT",
  "Green Tech, Edge AI & IoT",
  "Design digital systems that consider energy, carbon, latency, connectivity, sensing, local inference, and resilient operation at the edge.",
  "2026–2040",
  "Intermediate",
  "Green & Edge Technology",
  [
    "Measure energy and carbon as engineering constraints.",
    "Design carbon-aware and resource-efficient software workflows.",
    "Build IoT and edge architectures for intermittent connectivity.",
    "Understand TinyML and local inference trade-offs.",
    "Create an energy-aware sensing or automation capstone.",
  ],
  [
    { category: "Green Software", items: "Carbon intensity concepts, energy profiling, scheduling, efficient architecture" },
    { category: "Edge", items: "IoT sensors, MQTT concepts, TinyML, local inference, offline-first synchronization" },
  ],
  [
    {
      title: "Green Software & Carbon-Aware Computing",
      objective: "Treat energy and carbon as measurable software qualities.",
      summary: "Software consumes energy through compute, storage, networking, and hardware demand. Green engineering improves efficiency, shifts flexible work toward cleaner times or regions where appropriate, and avoids wasteful architecture.",
      concepts: ["energy efficiency", "carbon intensity", "utilization", "carbon-aware scheduling", "measurement"],
      practice: "Compare two deployment patterns and identify which design choices increase unnecessary compute, data movement, or idle capacity.",
      labTitle: "Energy-Aware Architecture Review",
      labDescription: "Create a simple sustainability scorecard.",
      labSteps: ["Map compute and data movement", "Identify idle or duplicate work", "Define one measurable efficiency metric", "Propose an improvement"],
      quiz: { question: "What makes green software engineering actionable?", options: ["A green logo", "Measuring and reducing resource use while meeting service goals", "Using more servers", "Disabling monitoring"], answerIndex: 1, explanation: "Sustainability becomes engineering work when resource use and outcomes are measurable." },
    },
    {
      title: "Edge Computing & Offline-First Design",
      objective: "Decide what should happen near the user instead of in a distant cloud.",
      summary: "Edge computing can reduce latency, bandwidth, privacy exposure, and dependency on constant connectivity. It also introduces device management, synchronization, and limited-resource constraints.",
      concepts: ["edge", "latency", "offline-first", "synchronization", "bandwidth"],
      practice: "Design a farm or field application that still records useful data when connectivity disappears for several hours.",
      labTitle: "Offline-First Flow",
      labDescription: "Map local storage, sync, and conflict handling.",
      labSteps: ["Define local actions", "Queue unsent records", "Set sync triggers", "Resolve duplicate or conflicting updates"],
      quiz: { question: "Why process data at the edge?", options: ["Only for decoration", "To reduce latency/bandwidth and operate during weak connectivity", "To remove all cloud services", "To avoid data validation"], answerIndex: 1, explanation: "Edge processing is valuable when local responsiveness, bandwidth, privacy, or resilience matter." },
    },
    {
      title: "Sensors, IoT Messaging & Device Data",
      objective: "Turn physical signals into trustworthy digital events.",
      summary: "IoT systems combine sensors, device identity, sampling, local filtering, messaging, ingestion, storage, and alerts. Data quality depends on calibration, timestamps, units, missing readings, and device health.",
      concepts: ["sensor", "sampling", "MQTT", "device identity", "calibration"],
      practice: "Design telemetry for soil moisture, temperature, energy use, or equipment health and define what makes a reading valid.",
      labTitle: "Sensor Data Contract",
      labDescription: "Create a schema and validation rules for device telemetry.",
      labSteps: ["Choose signals and units", "Add timestamp/device ID", "Define valid ranges", "Define missing-data behavior"],
      quiz: { question: "Why does calibration matter in IoT?", options: ["It changes the app color", "Sensor errors can create confident but wrong automation", "It increases password length", "It replaces timestamps"], answerIndex: 1, explanation: "Automation is only as trustworthy as the physical measurements it receives." },
    },
    {
      title: "TinyML & Edge AI",
      objective: "Understand when small local models are better than cloud inference.",
      summary: "TinyML and edge AI run inference on constrained devices or gateways. Benefits can include low latency, privacy, lower bandwidth, and resilience; constraints include memory, power, model size, update management, and drift.",
      concepts: ["TinyML", "quantization", "local inference", "model size", "drift"],
      practice: "Choose a simple classification or anomaly task and decide whether it belongs on-device, at a gateway, or in the cloud.",
      labTitle: "Edge AI Decision",
      labDescription: "Compare three deployment locations for one model.",
      labSteps: ["Define latency need", "Estimate data volume", "Assess privacy/connectivity", "Choose location and monitoring plan"],
      quiz: { question: "What is a common advantage of local inference?", options: ["Unlimited compute", "Lower latency and reduced dependence on connectivity", "No model updates", "Perfect accuracy"], answerIndex: 1, explanation: "Local inference trades constrained resources for responsiveness and resilience." },
    },
    {
      title: "Smart Energy, Storage & Resilient Systems",
      objective: "Connect digital control to changing energy systems.",
      summary: "Energy generation, storage, demand management, and microgrids increasingly use sensors, forecasting, optimization, and automated control. Digital builders need enough energy literacy to design useful monitoring without making unsafe control assumptions.",
      concepts: ["energy storage", "load", "forecasting", "microgrid", "safe control boundary"],
      practice: "Design a monitoring dashboard for a small solar-plus-battery site, separating observation from control actions that need qualified oversight.",
      labTitle: "Energy Monitoring Prototype",
      labDescription: "Define signals, alerts, and safe escalation.",
      labSteps: ["Choose energy KPIs", "Define thresholds", "Separate monitoring from control", "Add maintenance escalation"],
      quiz: { question: "What is the safest role for a beginner digital system in critical energy equipment?", options: ["Unrestricted autonomous control", "Monitoring, decision support, and bounded automation with qualified oversight", "Disable alarms", "Ignore sensor quality"], answerIndex: 1, explanation: "Critical physical systems need bounded automation and qualified human responsibility." },
    },
    {
      title: "Capstone: Carbon-Aware Edge Sensing",
      objective: "Integrate sensing, offline operation, local intelligence, and sustainability metrics.",
      summary: "The capstone builds a small edge sensing architecture that records data locally, performs a bounded inference or rule, synchronizes when possible, and documents energy and reliability trade-offs.",
      concepts: ["edge architecture", "offline sync", "local inference", "energy metric", "resilience"],
      practice: "Choose agriculture, cold-chain, buildings, energy, or environmental monitoring and build a low-bandwidth design.",
      labTitle: "Ship an Edge Prototype",
      labDescription: "Create a complete field-ready concept with evidence.",
      labSteps: ["Define sensors and schema", "Add offline data path", "Add local rule/model", "Measure resource use and test failure scenarios"],
      quiz: { question: "What distinguishes a strong edge capstone?", options: ["Cloud-only assumptions", "Measured trade-offs across connectivity, energy, latency, and reliability", "No failure testing", "Only a mockup"], answerIndex: 1, explanation: "Edge design is about explicit physical and operational constraints." },
    },
  ]
);

const blockchain = course(
  "blockchain-decentralized-systems",
  "Blockchain, Web3 & Decentralized Systems",
  "Blockchain & Decentralized Systems",
  "Study distributed ledgers, smart contracts, token standards, decentralized applications, oracles, storage, zero-knowledge concepts, and security with a problem-first rather than speculation-first approach.",
  "2026–2035",
  "Intermediate to Advanced",
  "Decentralized Technology",
  [
    "Explain consensus, transactions, keys, wallets, and state.",
    "Design and test smart contracts with explicit invariants.",
    "Evaluate when tokenization or decentralization is justified.",
    "Integrate dApps with wallets, storage, and external data.",
    "Recognize common contract and protocol security failures.",
  ],
  [
    { category: "Smart Contracts", items: "Solidity concepts, OpenZeppelin patterns, Foundry/Hardhat concepts" },
    { category: "Web3", items: "Wallets, viem/wagmi concepts, IPFS, oracles, zero-knowledge proof concepts" },
  ],
  [
    {
      title: "Distributed Ledgers, Keys & Consensus",
      objective: "Understand the trust model before writing a contract.",
      summary: "Blockchains replicate state across participants and use cryptography plus consensus to agree on valid transitions. Users control keys that authorize transactions, creating different operational and recovery risks from password-based systems.",
      concepts: ["ledger", "consensus", "public/private key", "transaction", "finality"],
      practice: "Trace the lifecycle of a signed transaction from wallet authorization through validation and final state change.",
      labTitle: "Transaction Explorer",
      labDescription: "Inspect a public test-network transaction and explain each field.",
      labSteps: ["Find a test transaction", "Identify sender/receiver", "Inspect fee and status", "Explain what the signature proves"],
      quiz: { question: "What authorizes a blockchain transaction?", options: ["A CSS class", "A cryptographic signature from the relevant private key", "A chart", "An email subject"], answerIndex: 1, explanation: "Digital signatures prove authorization without revealing the private key." },
    },
    {
      title: "Smart Contract Engineering",
      objective: "Treat contracts as immutable or hard-to-change production software.",
      summary: "Smart contracts encode state transitions that may directly control valuable assets. Strong development emphasizes simple logic, explicit invariants, access control, tests, upgrade decisions, and careful external calls.",
      concepts: ["Solidity", "state", "invariant", "access control", "upgradeability"],
      practice: "Write a contract specification in plain language before implementation, including who may change state and what must never happen.",
      labTitle: "Contract Specification",
      labDescription: "Define and test a small escrow-like state machine using test assets only.",
      labSteps: ["Write states and actors", "Define invariants", "Implement/test transitions", "Test unauthorized actions"],
      quiz: { question: "What is a smart-contract invariant?", options: ["A property that should always remain true", "A wallet logo", "A gas price", "A marketing slogan"], answerIndex: 0, explanation: "Invariants express safety properties that tests and reviews should protect." },
    },
    {
      title: "Tokens, Identity & Real-World Assets",
      objective: "Evaluate token standards and the legal/operational reality behind them.",
      summary: "Fungible and non-fungible token standards provide reusable interfaces, but a token is not automatically ownership of an off-chain asset or a compliant financial product. Real-world claims require governance and enforceable linkage.",
      concepts: ["ERC-20", "ERC-721/1155", "tokenization", "custody", "off-chain rights"],
      practice: "Compare a loyalty point, ticket, certificate, and financial claim and decide whether a blockchain token adds value.",
      labTitle: "Tokenization Decision Memo",
      labDescription: "Justify or reject tokenization for one use case.",
      labSteps: ["Define the asset/right", "Identify trust parties", "Compare centralized alternative", "Document custody and compliance questions"],
      quiz: { question: "What does a token alone guarantee about an off-chain asset?", options: ["Automatic legal ownership everywhere", "Only what the surrounding legal and operational system actually recognizes", "Perfect price stability", "No governance needs"], answerIndex: 1, explanation: "On-chain records need enforceable off-chain arrangements when they represent real-world rights." },
    },
    {
      title: "dApps, Oracles & Decentralized Storage",
      objective: "Connect on-chain logic to usable interfaces and external information.",
      summary: "dApps combine wallet interactions, frontend state, contract calls, decentralized or conventional storage, and oracles for external data. Every bridge between trust domains introduces failure assumptions.",
      concepts: ["dApp", "wallet connection", "oracle", "IPFS", "off-chain data"],
      practice: "Design a simple application that reads contract state and explain which information should remain off-chain.",
      labTitle: "dApp Architecture",
      labDescription: "Map frontend, wallet, contract, storage, and oracle boundaries.",
      labSteps: ["Draw components", "Classify on/off-chain data", "Define oracle assumptions", "Add fallback/error states"],
      quiz: { question: "Why are oracles security-sensitive?", options: ["They change font size", "They introduce external data into contract decisions", "They replace wallets", "They guarantee all facts"], answerIndex: 1, explanation: "Contracts may act on oracle inputs, so incorrect or manipulated data can change outcomes." },
    },
    {
      title: "Smart Contract Security & Zero-Knowledge Concepts",
      objective: "Recognize adversarial failure modes and privacy-preserving proof ideas.",
      summary: "Security reviews examine reentrancy, access control, arithmetic assumptions, oracle manipulation, flash-loan effects, upgrade keys, and economic incentives. Zero-knowledge proofs can demonstrate statements without revealing all underlying data, but add complexity.",
      concepts: ["reentrancy", "oracle manipulation", "economic attack", "zero-knowledge proof", "security audit"],
      practice: "Review a deliberately simple vulnerable contract description and identify technical and economic attack paths.",
      labTitle: "Threat Model a Protocol",
      labDescription: "Create an attacker-oriented review without exploiting real systems.",
      labSteps: ["List valuable assets", "List privileged roles", "Identify external dependencies", "Write mitigations and test cases"],
      quiz: { question: "What is the purpose of a zero-knowledge proof?", options: ["Reveal every secret", "Prove a statement while minimizing disclosure of underlying information", "Create free tokens", "Remove cryptography"], answerIndex: 1, explanation: "Zero-knowledge systems aim to prove validity without exposing unnecessary witness data." },
    },
    {
      title: "Capstone: Decentralization Fit & Prototype",
      objective: "Build only where the trust model justifies the complexity.",
      summary: "The capstone combines a decentralization decision, contract specification, tests, frontend integration, security review, and a clear explanation of what remains centralized or trusted.",
      concepts: ["decentralization fit", "contract testing", "dApp", "threat model", "governance"],
      practice: "Choose certificates, supply traceability, community coordination, digital identity, or another non-speculative problem and compare decentralized vs conventional designs.",
      labTitle: "Build & Defend the Prototype",
      labDescription: "Ship a test-network or simulated prototype with a written security review.",
      labSteps: ["Justify decentralization", "Implement minimal state machine", "Build interface and tests", "Publish threat model and limitations"],
      quiz: { question: "When is blockchain a strong architectural choice?", options: ["Whenever a database is needed", "When the problem benefits from shared state across parties that should not rely on one controller", "For every mobile app", "To avoid testing"], answerIndex: 1, explanation: "The architecture is most defensible when multi-party trust and shared state justify its trade-offs." },
    },
  ]
);

const robotics = course(
  "robotics-autonomous-systems",
  "Robotics, Edge AI & Autonomous Systems",
  "Robotics & Autonomous Systems",
  "Learn how sensing, perception, planning, control, embedded/edge AI, safety, and human supervision combine in robots and autonomous machines.",
  "2026–2040",
  "Intermediate",
  "Robotics",
  [
    "Model the sense-think-act loop of an autonomous system.",
    "Work with coordinate frames, sensors, actuators, and robotics middleware concepts.",
    "Understand perception and edge-inference pipelines.",
    "Design bounded planning and control with safety constraints.",
    "Build a simulated autonomous-system capstone.",
  ],
  [
    { category: "Robotics", items: "ROS 2 concepts, simulation, sensors, actuators, coordinate frames, path planning" },
    { category: "AI", items: "Computer vision, sensor fusion, edge inference, anomaly detection, human oversight" },
  ],
  [
    {
      title: "Sense–Think–Act Foundations",
      objective: "Decompose autonomy into observable subsystems.",
      summary: "Robots sense the environment, estimate state, choose actions, and actuate physical systems. Good designs make uncertainty, timing, failure, and safe stopping explicit.",
      concepts: ["sensor", "state estimation", "planner", "controller", "actuator"],
      practice: "Break a delivery robot or agricultural rover into sensing, state, planning, control, and safety components.",
      labTitle: "Autonomy Block Diagram",
      labDescription: "Create a complete sense-think-act architecture.",
      labSteps: ["List sensors", "Define estimated state", "Define planner inputs", "Add safe-stop path"],
      quiz: { question: "What closes the loop in a robotic control system?", options: ["Feedback from sensors/state", "A static poster", "A password reset", "A database backup alone"], answerIndex: 0, explanation: "Feedback lets the system compare intended and observed behavior and adjust actions." },
    },
    {
      title: "Robotics Software, Frames & Simulation",
      objective: "Coordinate multiple components without requiring expensive hardware.",
      summary: "Robotics middleware organizes messages, services, transforms, and components. Coordinate frames let sensors and actuators reason about the same physical world, while simulation accelerates safe testing.",
      concepts: ["ROS 2 concepts", "topic", "service", "coordinate frame", "simulation"],
      practice: "Model a simulated robot with a sensor topic, control command, and map/world frame.",
      labTitle: "Simulated Robot Interface",
      labDescription: "Design message flows between perception and control.",
      labSteps: ["Define components", "Define message topics", "Define coordinate frames", "Test simulated failure messages"],
      quiz: { question: "Why are coordinate frames important?", options: ["They define consistent spatial relationships between sensors, robot, and world", "They encrypt messages", "They increase battery capacity", "They replace simulation"], answerIndex: 0, explanation: "Robots need consistent spatial references to combine sensor data and plan movement." },
    },
    {
      title: "Perception, Computer Vision & Sensor Fusion",
      objective: "Turn noisy physical signals into useful state estimates.",
      summary: "Autonomous systems combine cameras, depth, inertial, position, proximity, and other sensors. Perception models are uncertain, so fusion, confidence, validation, and degraded modes matter.",
      concepts: ["computer vision", "sensor fusion", "confidence", "localization", "degraded mode"],
      practice: "Compare camera-only and multi-sensor approaches for navigating in poor lighting or dust.",
      labTitle: "Perception Reliability Matrix",
      labDescription: "Map sensors to conditions and fallback behavior.",
      labSteps: ["List operating conditions", "Score sensor reliability", "Define fusion/fallback", "Specify when autonomy must stop"],
      quiz: { question: "Why combine multiple sensors?", options: ["To guarantee perfection", "Different sensors can compensate for each other's weaknesses", "To remove uncertainty", "To avoid calibration"], answerIndex: 1, explanation: "Sensor fusion can improve robustness when individual sensors fail under different conditions." },
    },
    {
      title: "Planning, Control & Bounded Autonomy",
      objective: "Separate goal selection, path planning, control, and safety constraints.",
      summary: "Planning chooses a route or sequence, while controllers translate desired behavior into actuator commands. Constraints for speed, geofencing, obstacle distance, battery, and emergency stop bound autonomy.",
      concepts: ["path planning", "control", "constraint", "geofence", "fail-safe"],
      practice: "Design a bounded navigation policy for a campus delivery rover using safe zones and human escalation.",
      labTitle: "Safe Autonomy Policy",
      labDescription: "Define operating envelope and stop conditions.",
      labSteps: ["Define goal and route", "Set speed/zone constraints", "Define obstacle response", "Define human takeover conditions"],
      quiz: { question: "What is bounded autonomy?", options: ["Autonomy with explicit operating limits and escalation", "Unlimited self-modification", "No safety constraints", "A manual spreadsheet"], answerIndex: 0, explanation: "Boundaries keep autonomous behavior within tested conditions and preserve escalation paths." },
    },
    {
      title: "Safety, Security & Human-Robot Interaction",
      objective: "Design for physical consequences and adversarial inputs.",
      summary: "Robotics combines cyber and physical risk. Systems need safe states, authenticated updates, protected control channels, collision-aware behavior, user signaling, emergency controls, and post-incident evidence.",
      concepts: ["functional safety", "cyber-physical security", "emergency stop", "human factors", "audit log"],
      practice: "Threat-model a remotely updated autonomous machine and identify both cyber compromise and accidental physical failure.",
      labTitle: "Safety Case Lite",
      labDescription: "Create hazards, mitigations, and verification evidence.",
      labSteps: ["Identify hazards", "Estimate consequence", "Add preventive controls", "Define emergency and recovery procedure"],
      quiz: { question: "Why does robot cybersecurity have physical importance?", options: ["Compromised commands can affect real actuators and people", "Robots never use networks", "Only websites need security", "Physical systems cannot be attacked"], answerIndex: 0, explanation: "Cyber failures in connected machines can cause physical outcomes." },
    },
    {
      title: "Capstone: Autonomous System in Simulation",
      objective: "Demonstrate perception, planning, control, and safe fallback without expensive hardware.",
      summary: "The capstone builds a simulated agricultural, inspection, warehouse, mobility, or delivery system and evaluates it against normal and failure scenarios.",
      concepts: ["simulation", "autonomy", "edge AI", "safety case", "test scenarios"],
      practice: "Choose one narrow task and make the operating conditions, success metric, and stop conditions explicit.",
      labTitle: "Autonomous Mission Demo",
      labDescription: "Run a simulated mission and document evidence.",
      labSteps: ["Define mission", "Implement/mock perception and planning", "Test normal and degraded cases", "Publish metrics, hazards, and lessons"],
      quiz: { question: "Why is simulation valuable in robotics education?", options: ["It enables repeatable testing of risky or expensive scenarios", "It eliminates all need for real validation", "It guarantees hardware behavior", "It removes safety engineering"], answerIndex: 0, explanation: "Simulation supports repeatable learning and failure testing before hardware exposure." },
    },
  ]
);

const spatialTwins = course(
  "spatial-computing-digital-twins",
  "Spatial Computing, XR & Digital Twins",
  "Spatial Computing & Digital Twins",
  "Create future interfaces and operational models that connect 3D spaces, sensors, simulation, XR interaction, and real-world system data.",
  "2027–2040",
  "Intermediate",
  "Spatial Technology",
  [
    "Explain AR, VR, mixed reality, spatial mapping, and digital-twin concepts.",
    "Design accessible spatial interactions around real user tasks.",
    "Connect sensor/IoT data to a virtual representation.",
    "Use simulation and AI for scenario testing without confusing models with reality.",
    "Prototype a useful training, operations, design, or education experience.",
  ],
  [
    { category: "Spatial", items: "WebXR/Unity/Unreal concepts, 3D assets, spatial anchors, mapping, interaction design" },
    { category: "Digital Twins", items: "IoT data, time-series state, simulation, dashboards, AI-assisted scenario analysis" },
  ],
  [
    {
      title: "Spatial Computing & XR Foundations",
      objective: "Understand the continuum from screens to immersive environments.",
      summary: "Spatial computing places digital information in relation to physical or simulated space. AR overlays, VR environments, and mixed-reality interactions require tracking, rendering, spatial anchors, input, comfort, and task-focused design.",
      concepts: ["AR", "VR", "mixed reality", "spatial anchor", "tracking"],
      practice: "Choose a task that benefits from spatial context and explain why a normal 2D interface is insufficient or still preferable.",
      labTitle: "Spatial Use-Case Filter",
      labDescription: "Evaluate five ideas and reject novelty-only use cases.",
      labSteps: ["Define user task", "Identify spatial benefit", "Assess hardware/access limits", "Choose XR or 2D intentionally"],
      quiz: { question: "When is spatial computing most justified?", options: ["Whenever 3D looks impressive", "When spatial context materially improves the user's task", "For every text form", "When usability testing is unavailable"], answerIndex: 1, explanation: "Spatial interfaces should solve spatial or embodied problems rather than add unnecessary complexity." },
    },
    {
      title: "3D Interaction, Accessibility & Human Factors",
      objective: "Design spatial interfaces people can understand and tolerate.",
      summary: "Immersive design must consider field of view, reach, locomotion, motion sickness, readability, hand/voice/controller input, physical safety, accessibility, and clear feedback.",
      concepts: ["spatial UX", "comfort", "accessibility", "input modality", "feedback"],
      practice: "Redesign a confusing immersive menu around one-handed use, seated use, and a clear exit path.",
      labTitle: "XR Interaction Prototype",
      labDescription: "Storyboard a short spatial task with accessibility alternatives.",
      labSteps: ["Define task steps", "Choose input methods", "Add comfort/accessibility options", "Test with a non-expert"],
      quiz: { question: "Why does comfort belong in XR product design?", options: ["Immersive interfaces can cause fatigue or motion discomfort", "It improves database indexes", "It replaces security", "It only affects colors"], answerIndex: 0, explanation: "Physical comfort directly affects whether immersive systems are usable." },
    },
    {
      title: "Mapping, Sensors & Spatial Data",
      objective: "Represent the physical environment reliably enough for useful overlays.",
      summary: "Spatial systems use cameras, depth, inertial sensors, GPS, maps, anchors, and sometimes external IoT data. Coordinate systems, drift, occlusion, uncertainty, and privacy affect reliability.",
      concepts: ["SLAM concepts", "depth", "coordinate system", "occlusion", "spatial privacy"],
      practice: "Design a campus navigation or maintenance overlay and identify what data can become stale or spatially inaccurate.",
      labTitle: "Spatial Data Contract",
      labDescription: "Define positions, timestamps, confidence, and refresh rules.",
      labSteps: ["Define coordinate reference", "Add timestamp/confidence", "Handle stale anchors", "Protect unnecessary location data"],
      quiz: { question: "Why should spatial data include freshness/confidence information?", options: ["Physical environments and tracking estimates can change", "Coordinates are always exact", "It increases file size only", "It disables sensors"], answerIndex: 0, explanation: "Spatial decisions depend on whether a position estimate is current and reliable." },
    },
    {
      title: "Digital Twins & Operational State",
      objective: "Connect a virtual representation to real system data without overstating fidelity.",
      summary: "A digital twin represents a physical asset, process, place, or system using models plus current or historical data. Useful twins define which state is mirrored, update frequency, source quality, and decisions the representation supports.",
      concepts: ["digital twin", "telemetry", "state model", "time series", "model fidelity"],
      practice: "Design a twin for a greenhouse, building room, machine, or logistics asset and specify which state should be real-time versus simulated.",
      labTitle: "Twin State Model",
      labDescription: "Map physical signals to virtual state and actions.",
      labSteps: ["Choose asset/process", "Define state variables", "Set update frequency", "Document model limitations"],
      quiz: { question: "What distinguishes a useful digital twin from a static 3D model?", options: ["A connection to meaningful operational state/data", "More polygons only", "A brighter background", "No real-world reference"], answerIndex: 0, explanation: "Digital twins connect a representation to the evolving state of a real system or process." },
    },
    {
      title: "Simulation, AI & Scenario Intelligence",
      objective: "Use models for exploration while keeping evidence boundaries clear.",
      summary: "Digital twins can support simulation, anomaly detection, forecasting, optimization, and training. AI-generated scenarios remain hypotheses until validated against physical evidence and operational constraints.",
      concepts: ["simulation", "forecasting", "anomaly detection", "scenario", "validation"],
      practice: "Create three what-if scenarios for a twin and specify which assumptions require real-world validation before action.",
      labTitle: "Scenario Lab",
      labDescription: "Compare baseline, stress, and intervention scenarios.",
      labSteps: ["Define baseline", "Change one variable", "Record predicted effect", "Define real-world validation data"],
      quiz: { question: "How should a simulated prediction be treated?", options: ["As guaranteed reality", "As model-based evidence that needs validation", "As a legal certificate", "As a password"], answerIndex: 1, explanation: "Simulations are useful decision aids, but their assumptions and fidelity limit certainty." },
    },
    {
      title: "Capstone: Spatial Operations or Learning Twin",
      objective: "Prototype a spatial experience connected to meaningful state and user outcomes.",
      summary: "The capstone combines spatial UX, a state model, live or simulated telemetry, scenario testing, accessibility, and a clear explanation of what the experience improves.",
      concepts: ["XR prototype", "digital twin", "telemetry", "user testing", "scenario analysis"],
      practice: "Choose training, campus navigation, agriculture, facilities, manufacturing, tourism, or education and prototype one high-value task.",
      labTitle: "Build a Useful Spatial Twin",
      labDescription: "Deliver a prototype, test script, and evidence report.",
      labSteps: ["Define one user task", "Create spatial/twin model", "Connect sample state data", "Test usability and document limitations"],
      quiz: { question: "What makes the capstone credible?", options: ["Visual effects alone", "A user task, meaningful state data, testing, and documented limitations", "No users", "No data model"], answerIndex: 1, explanation: "A useful spatial product connects technology to a verified task and evidence." },
    },
  ]
);

export const futureSkillCourses: FutureSkillCourse[] = [
  responsibleAi,
  noCodeAutomation,
  cloudArchitecture,
  cyberAiCloud,
  quantum,
  greenEdge,
  blockchain,
  robotics,
  spatialTwins,
];

export const futureSkillsBySlug: Record<string, FutureSkillCourse> = Object.fromEntries(
  futureSkillCourses.map((item) => [item.slug, item])
);
